### ISSUE TITLE
How to run on Win10?

### ISSUE THREAD

**Issue by serkan420** [bumbummen99/southparkdownloader#10]
Hi,

I'm on Win10, the instructions are telling me to install "Microsoft Visual C++ 2010 Redistributable Package (x86)", which I can't install because there is a newer version installed.

I can't run any of the files given, the instructions are speaking of an "executable". Which one is it and how do I execute it?

Thanks and best regards

**Comment by bumbummen99** [comment]
Wich version are you using? The GUI one might still be buggy, its kind of a WIP. 
But in any version for Windows there should be an .exe included wich you can run.

**Comment by serkan420** [comment]
I have downloaded the whole "southparkdownloader-master"-zip at the time I have commented. I couldn't find any .exe in there.
Is it the wrong package or is it maybe in some directory where I haven't looked yet?

Thanks again and best regards

**Comment by bumbummen99** [comment]
I think you have downloaded the wrong file / source code :) To download the windows build just look for a `win-x64` file in the latest Release:

https://github.com/bumbummen99/southparkdownloader/releases

**Comment by serkan420** [comment]
Ah, gotcha! That resolved my question. Thanks :)
