### ISSUE TITLE
YouTubeDLC not downloading latest

### ISSUE THREAD

**Issue by bumbummen99** [bumbummen99/southparkdownloader#11]
The software will try to download YouTube DL Community from
`https://github.com/blackjack4494/youtube-dlc/releases/latest/download/youtube-dlc.exe`

For some reason, this is not the same version as the latest release from their GitHub (even if the URL does say so) and will result in an outdated / incompatible version.

**Comment by TH42** [comment]
> For some reason, this is not the same version as the latest release from their GitHub (even if the URL does say so) and will result in an outdated / incompatible version.

This doesn't seem to be an issue anymore. I just did a fresh setup with the command line version and the file downloaded is identical to the one from the latest release.
