### ISSUE TITLE
setUpIndex @ Setup.cs failed

### ISSUE THREAD

**Issue by steffensiebert** [bumbummen99/southparkdownloader#14]
The Setup.cs tries to download the data.db for the IndexFile from "https://bumbummen99.github.io/southparkdownloader/data.db" but the Site responds 404, because you deleted it in the last commit.

(PS: Thanks for changing the yt-dl to yt-dlp 👍 )

**To Reproduce**
1. Checkout a clean repo
2. Run SouthParkDLCommandLine
3. setUpIndex() fails

**Desktop (please complete the following information):**
 - OS: Windows10

**Comment by bumbummen99** [comment]
Damn, i thought the databases were split into german.db and english.db. I will have to look into that.

Edit: The .db files are clean, it is the language switch that is currently missing.

**Comment by bumbummen99** [comment]
Please try with 1.7.3

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
