### ISSUE TITLE
Dead link in the readme

### ISSUE THREAD

**Issue by pifopi** [bumbummen99/southparkdownloader#16]
Hello

**Describe the bug**
The link to the Microsoft Visual C++ 2010 Redistributable Package (x86) in the readme is dead. I'm wondering if it's the real version that is needed (because it is old) or if a newer one could be used instead !

Thanks for your work :)

**Comment by bumbummen99** [comment]
I'll look into it. It has been some time since i did .Net but as far as i remember there is a new unified installer that has all required redist packages there are. I will link that one.

**Comment by bumbummen99** [comment]
Should be done with 4f5e0c7

**Comment by pifopi** [comment]
Thanks a lot for the link ! Is it intended to be in german ?
THe english one can be found here : https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by bumbummen99** [comment]
> Thanks a lot for the link ! Is it intended to be in german ? THe english one can be found here : https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Hehe yeah i did not look twice, should be eng as thats understandable for everyone. Gonna replace it

**Comment by pifopi** [comment]
Thanks a lot !
