### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by JoKerIsCraZy** [bumbummen99/southparkdownloader#19]
The Downloader dont work (Windows Version and Linux)

Any idea what i can do to fix it?

This is the errors i get when i try to run it

"$index update
Updating episode index...
Loaded episode index.
$download
[S1E3] Starting download 3 Wie werde ich ein Kampfkoloss?
[S1E4] Starting download 4 Ein Heim für Tiertunten
[S1E1] Starting download 1 Cartman und die Analsonde
[S1E2] Starting download 2 Knall endlich den Hasen ab!
WARNING: Falling back on generic information extractor.
WARNING: Falling back on generic information extractor.
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://www.southpark.de/folgen/er4a32/south-park-wie-werde-ich-ein-kampfkoloss-staffel-1-ep-3
[S1E3] YoutubeDL failed.
[S1E3] No video files to merge!
[S1E5] Starting download 5 Tanz der Mutanten
ERROR: Unsupported URL: https://www.southpark.de/folgen/4rcpa5/south-park-ein-heim-fuer-tiertunten-staffel-1-ep-4
[S1E4] YoutubeDL failed.
[S1E4] No video files to merge!
[S1E6] Starting download 6 Wer killt Opa?
ERROR: Unsupported URL: https://www.southpark.de/folgen/940f8z/south-park-cartman-und-die-analsonde-staffel-1-ep-1
[S1E1] YoutubeDL failed.
[S1E1] No video files to merge!"

**Comment by mkaletsch** [comment]
For me it isn't working either.

Looks like this:

SouthParkDL v1.7.3.0
SouthParkDL is ready!
Loaded episode index.
$download
[S1E2] Starting download 2 Knall endlich den Hasen ab!
[S1E1] Starting download 1 Cartman und die Analsonde
[S1E4] Starting download 4 Ein Heim für Tiertunten
[S1E3] Starting download 3 Wie werde ich ein Kampfkoloss?
[S1E2] YoutubeDL failed.
[S1E2] No video files to merge!
[S1E4] YoutubeDL failed.
[S1E4] No video files to merge!
[S1E3] YoutubeDL failed.
[S1E3] No video files to merge!
[S1E1] YoutubeDL failed.
[S1E1] No video files to merge!
[S1E5] Starting download 5 Tanz der Mutanten
[S1E6] Starting download 6 Wer killt Opa?
[S1E7] Starting download 7 Her mit dem Hirn!
[S1E8] Starting download 8 Ein Fettwanst in Äthiopien
[S1E7] YoutubeDL failed.
[S1E7] No video files to merge!
[S1E6] YoutubeDL failed.
[S1E6] No video files to merge!
[S1E5] YoutubeDL failed.
[S1E5] No video files to merge!
[S1E8] YoutubeDL failed.
[S1E8] No video files to merge!

**Comment by lnx00** [comment]
Not working for me neither. I get [JoKerIsCraZy](https://github.com/JoKerIsCraZy)'s issue when using the linux version and [mkaletsch](https://github.com/mkaletsch)'s issue when using the windows version.

**Comment by bumbummen99** [comment]
Are you guys using the youtube dlp switch? Youtube dl main project seems discontinued.
I am currently working on a rewrite of this project anyways that will make maintaining & install it 100% easier.

**Comment by mkaletsch** [comment]
I used the youtube-dl.exe (not sure if this is the same as youtube-dlp switch :D)

I'm looking forward for your new project

**Comment by lnx00** [comment]
I have replaced the youtube-dl.exe with youtube-dlp and it seems to work now.
What do you mean with "youtube dlp switch"? Is there some settings page where we can enable youtube-dlp or is replacing the youtube-dl.exe the only solution?

**Comment by mkaletsch** [comment]
@lnx00 you're right, replacing the youtube-dl.exe with youtube-dlp works! Thanks.

Is there a way to get both audio files? English and german? Right now its only german :) Would be awesome!

I guess it's always downloading the original video-bitrate from the stream? I also prefer a mkv file, is there a way to say ffmpeg to make directly an mkv file?

**Comment by JoKerIsCraZy** [comment]
Replacing the youtube-dl.exe with the youtube-dlp worked thanks

**Comment by JoKerIsCraZy** [comment]
> Are you guys using the youtube dlp switch? Youtube dl main project seems discontinued. I am currently working on a rewrite of this project anyways that will make maintaining & install it 100% easier.

Is there by the way an option to only download only one Episode?

**Comment by bumbummen99** [comment]
> I have replaced the youtube-dl.exe with youtube-dlp and it seems to work now. What do you mean with "youtube dlp switch"? Is there some settings page where we can enable youtube-dlp or is replacing the youtube-dl.exe the only solution?

Yes, if you use the argument `--ytdlc` for startup it will automatically download youtube-dlp instead of dlc.

**Comment by Mxgra** [comment]
Guys, how do I replace youtube-dl.exe with youtube-dlp? :D I uninstalled and installed the new yt-dlp, but the Downloader doesnt recognize it. I'm on osx, openend the cli with -ytdlc, also tried download command with the argument... nothing works, it always wants to use youtube-dl

**Comment by bumbummen99** [comment]
> Guys, how do I replace youtube-dl.exe with youtube-dlp? :D I uninstalled and installed the new yt-dlp, but the Downloader doesnt recognize it. I'm on osx, openend the cli with -ytdlc, also tried download command with the argument... nothing works, it always wants to use youtube-dl

On linux/macos it does expect to be `youtube-dl` so you got to make a link from youtube-dl to youtube-dlp. The flag only works for windows where it does download the dependencies automatically.

**Comment by Mxgra** [comment]
thanks, so I'd need to either change the command in the source code and rebuild it, or make a make the link on the operating system itself? If I just use the alias command it doesn't work, I suppose it's not getting moved over to the CLI

**Comment by bumbummen99** [comment]
> thanks, so I'd need to either change the command in the source code and rebuild it, or make a make the link on the operating system itself? If I just use the alias command it doesn't work, I suppose it's not getting moved over to the CLI

Command on linux is just `youtube-dl`

https://github.com/bumbummen99/southparkdownloader/blob/02f701342d855c96fa1352ffa579b8f022ca865d/SouthParkDLCore/Commands/Executables/YoutubeDL.cs#L9

So you got to replace your installed `youtube-dl`'s link to `youtube-dlp`. Check where the link in your PATH is with `which youtube-dl` and then just replace it with a link to `which youtube-dlp` or whatever the command is.

**Comment by Mxgra** [comment]
yes but my problem is, that if I link youtube-dl to yt-dlp, the link (or alias) only persists for the interactive shell, or terminals. It's not persistent your program. I think one would have to change the command "youtube-dl" to "yt-dlp" in the file you posted and then rebuild the program. But I dont know c# or dotnet...😅 Tried my luck for a time now and think I'll jsut give it a rest

**Comment by bumbummen99** [comment]
> yes but my problem is, that if I link youtube-dl to yt-dlp, the link (or alias) only persists for the interactive shell, or terminals. It's not persistent your program. I think one would have to change the command "youtube-dl" to "yt-dlp" in the file you posted and then rebuild the program. But I dont know c# or dotnet...sweat_smile Tried my luck for a time now and think I'll jsut give it a rest

How is the link only available in the current shell? Should actually modify your hard drive.
`ln -s $(which youtube-dl) $(which yt-dlp)`

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
