### ISSUE TITLE
Episodes muxing forever / Input string Error

### ISSUE THREAD

**Issue by Dext00** [bumbummen99/southparkdownloader#20]
Hey, most of the episodes have been downloaded and put together. Some took multiple tries. For some, this error comes (Processing episode error: Input string was not in a correct format.) or this text appears and it doesn't go any further
([S10E9] Finished download
[S10E9] Start muxing).
I have already updated the index.

 - Windows

**Comment by bumbummen99** [comment]
Can you check it's folder (with hidden files enabled) and show what files are in it?

**Comment by Dext00** [comment]
The error "Processing episode error: Input string was not in a correct format." appears only for episodes that are currently unavailable.

As an example S10E09 Folder
![grafik](https://user-images.githubusercontent.com/104714940/166147827-5ccce4d6-333f-4085-a764-5a2f00dd543c.png)
![grafik](https://user-images.githubusercontent.com/104714940/166147839-8382ccca-4c7c-447c-884a-019e38d65e96.png)

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
