### ISSUE TITLE
Mulithreaded FFMpeg leads to problems [Solution given]

### ISSUE THREAD

**Issue by steffensiebert** [bumbummen99/southparkdownloader#21]
I've made two changes here, because ffmpeg crashes sometimes on multithreaded operations (os: windows).

Episode.cs: L137 (et seq)
`

            lock (lockname)
            {
                Console.WriteLine(ConsoleTag + "locked ffmpeg");
                Console.WriteLine(ConsoleTag + " Start muxing");
                FFMpeg ffmpeg = new FFMpeg(this.Directory);
                if (!ffmpeg.Mux(videoFiles, this.FileName + this.Extension))
                {
                    Console.WriteLine(ConsoleTag + " ffmpeg failed for some reason.");
                    return;
                }
            }
            Console.WriteLine( ConsoleTag + "lock removed");
`

Furthermore to prevent a deadlock i added another optional parameter to the Executable.cs Run method, which defines a timeout.
Keep in mind, that Executable.cs is extended by YoutubeDL.cs and FFMpeg.cs (we only want a timeout at FFMpeg.cs, because downloading with slow internet connection could kill the process here)
The optional timeout parameter is used at Executable.cs run method:
Line 67:
`

            if (timeout != 0)
            {
                process.WaitForExit(timeout);
            }
            else
            {
               process.WaitForExit();
             }

`

**Comment by steffensiebert** [comment]
Currently i am using no timeout on the Run method call from YoutubeDl.cs  and a 10 sec timeout on FFMpeg.cs. (10 sec is a little bit too much, but i thought if a very slow toaster with a HDD runs this script the ffmpeg operation could take a while)

**Comment by bumbummen99** [comment]
What exactly is the state of ffmpeg when it does crash? Did you try/observe it when running it manually? Just asking as there might be a way to just catch the crash instead of limiting the totatl time.

**Comment by steffensiebert** [comment]
Currently I am not sure, what's the problem with ffmpeg running multithreaded and to reproduce you need to run the debug mode with multiple threads and have luck with the timing. If you are aware of "bottlenecking" the process, I can confirm that using the lock in combination with a 10 sec timeout on the process.WaitForExit the whole usage of this command line tool is improved. If this is not added, during the download process all tasks gets stuck and you have to restart manually again. The current state of this tool is without it unusable, because you have to manually download and merge 10%-20% of the episodes. With these changes you can shrink the error rate with a few lines of code. (I am not saying that all problems are removed by this, a few episodes lead to problems with ffmpeg, but I don't know why.)
(Using the German db)

**Comment by bumbummen99** [comment]
After a bit of researching this does sound as it might be what is actually going on here
https://stackoverflow.com/a/7608823

**Comment by bumbummen99** [comment]
@KingStoffen Can you please try #22 and check if it does fix the problem?

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
