### ISSUE TITLE
Allow season and/or episode filter

### ISSUE THREAD

**Issue by FireEmerald** [bumbummen99/southparkdownloader#23]
Downloading all episodes from all seasons takes a loong time and a user may only want a specific season.
This is really easy to implement, it is just the question which filter would we like to support and how should the command line syntax look like.

Examples:
```
download season=1-2,6-9
download filter=s1-s2e05,s6e07-s9e02
```

**Comment by bumbummen99** [comment]
Sorry but i am not actively working on this project anymore as i am currently working on a rewrite in TypeScript. However if you want to create a PR with the functionality i am always open for that 👍

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
