### ISSUE TITLE
Cannot setup SSL connection running on ubuntu 22.04

### ISSUE THREAD

**Issue by fermat2a** [bumbummen99/southparkdownloader#24]
**Describe the bug**
When starting SouthParkDLCommandLine under Ubuntu 22.04 I get following output:

```
SouthParkDL v1.7.3.0
SouthParkDL is ready!
Setting up dependencies.
Please make sure youtube-dl is installed.
You can install it by typing 'sudo apt install youtube-dl'.
Downloading & extracting ffmpeg...
Unsupported operating detected, can not install ffmpeg automatically!
Please make sure ffmpeg is installed or install it manually.
You can install it by installing the ffmpeg packe using your PM. For Debian devirates typing 'sudo apt install ffmpeg' should suffice.
Updating episode index...
Unhandled exception. System.Net.WebException: The SSL connection could not be established, see inner exception. Authentication failed, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:module_run:unknown module name
   at Interop.SslInitializer..cctor()
```

I guess I need to install a package?

**To Reproduce**
Download the software and run it under ubuntu 22.04

**Expected behavior**
Downloader should start

**Desktop (please complete the following information):**
Ubuntu Linux 22.04

**Comment by bumbummen99** [comment]
Looks like something is going on with the GitHub TLS certificate. You can try to manually download the episode index file from here
https://github.com/bumbummen99/southparkdownloader/tree/master/docs
Coose one of the .db files and name it `data.db` inside /data

**Comment by fermat2a** [comment]
I downloaded the file and it seems to start. Do you want to keep the ticket open to repair the TLS problem?

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
