### ISSUE TITLE
File not found after muxing

### ISSUE THREAD

**Issue by fermat2a** [bumbummen99/southparkdownloader#25]
**Describe the bug**
I installed SouthParkDLCommandLine-1.7.4-linux-x64 under Ubuntu 22.04. I installed also youtube-dl (manually to get the most recent version) and ffmpeg (using apt-get install ffmpeg). The I started it:

```
$ /SouthParkDLCommandLine
SouthParkDL v1.7.3.0
SouthParkDL is ready!
Loaded episode index.
$
```

I called download to start the download of the files and it gave me following output:

```
$download
[S1E3] Starting download 3 Wie werde ich ein Kampfkoloss?
[S1E1] Starting download 1 Cartman und die Analsonde
[S1E4] Starting download 4 Ein Heim für Tiertunten
[S1E2] Starting download 2 Knall endlich den Hasen ab!
[S1E3] Finished download
[S1E3] Start muxing
[S1E3] Successfully muxed episode to "/home/fermat/usr/SouthParkDLCommandLine-1.7.4-linux-x64/data/1/3/S1E3-Wie werde ich ein Kampfkoloss.mp4"
[S1E3] Adding meta information.
Processing episode error: Could not find file '/home/fermat/usr/SouthParkDLCommandLine-1.7.4-linux-x64/data/1/3/S1E3-Wie werde ich ein Kampfkoloss.mp4'.
...
```

It does the same for all other files it downloads, I cannot find any mp4 files later on. In '/home/fermat/usr/SouthParkDLCommandLine-1.7.4-linux-x64/data/1/3 I find some other files: dlfinish, ffmpeg.log, mergefinish, ytdl.log. All of the files are empty but ffmpeg.log:

```
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
files.txt: Invalid data found when processing input
```

Any Idea what is going wrong?

**Desktop (please complete the following information):**
Ubuntu Linux 22.04

**Comment by Mantarochen01** [comment]
Same problem here on WIN11. 

CL states finished download to the directory, upon opening it I just have the txt and log files in there as you mentioned @fermat2a . 

Download seems to not happen at all based on the fact that my disk space is not getting filled. The program uses almost 24% CPU on a Ryzen9 5900X.... Idk how that is a thing, if the application hasnt even downloaded something to process....

**Comment by bumbummen99** [comment]
> Same problem here on WIN11.
> 
> CL states finished download to the directory, upon opening it I just have the txt and log files in there as you mentioned @fermat2a .
> 
> Download seems to not happen at all based on the fact that my disk space is not getting filled. The program uses almost 24% CPU on a Ryzen9 5900X.... Idk how that is a thing, if the application hasnt even downloaded something to process....

Yeah the code is quite...special. I was working on a rewrite of this project using TypeScript and provide it as a docker image so you only have to install docker and go - had no time to finish it yet tho.

**Comment by Mantarochen01** [comment]
> Yeah the code is quite...special. I was working on a rewrite of this project using TypeScript and provide it as a docker image so you only have to install docker and go - had no time to finish it yet tho.

I mean to be honest here, I'm a system integrator trainee and have the upmost respect for my dev-trainee colleagues that can sit in front of visual studio and make something happen :D. 

I tap out at the higher end bash script level. So anyone making stuff like this in his free time to then publish it for free has a red Cape on 🦸. Even if the code takes all my CPU at once with a big boom, still a win on my book :) .

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
