### ISSUE TITLE
Command Line Version and GUI Version dont download anything

### ISSUE THREAD

**Issue by Mantarochen01** [bumbummen99/southparkdownloader#26]
**Describe the bug**
The Tool doesnt download any files, after stating "muxing" is done, a "file not found" error appears.

**To Reproduce**
Start the download

**Expected behavior**
Episode should be downloaded

**Screenshots**

```
Finished download
[S3E5] Start muxing
[S3E5] Successfully muxed episode to "C:\Users\***Desktop\Downloader\SouthParkDLCommandLine-1.7.4-win-x64\data/3/5/S3E5-Tweek gegen Craig.mp4"
[S3E5] Adding meta information.
Processing episode error: Could not find file 'C:\Users\***Desktop\Downloader\SouthParkDLCommandLine-1.7.4-win-x64\data\3\5\S3E5-Tweek gegen Craig.mp4'.
```
Username replaced with ***

**Desktop (please complete the following information):**
 - OS: WIN11

**Comment by Mantarochen01** [comment]
Is this project still alive? Last contribution from bumbumm was 3 months ago....

**Comment by LeonSt3** [comment]
I think it's not really alive. I've tried to "quick-fix" it and made a Pull-Request. But I can't say for sure if it's working for everyone.

**Comment by Mantarochen01** [comment]
> I think it's not really alive. I've tried to "quick-fix" it and made a Pull-Request. But I can't say for sure if it's working for everyone.

Thanks for fixing, or trying to fix it ;). Sadly I'm as good with code as a sewer rat. 
I don't even know what do do with the uncompiled code you published. So this comments just sits here as ty, and to get some attention to this maybe ;). 

Greetings.

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).

**Comment by KatzeMau** [comment]
> ## Repository Deprecated Notice
> 
> This repository is no longer maintained. All issues, including this one, will be closed.
> 
> Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.
> 
> For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).

When will the new repo work ?
Keep it up :)

**Comment by bumbummen99** [comment]
> > ## Repository Deprecated Notice
> > This repository is no longer maintained. All issues, including this one, will be closed.
> > Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.
> > For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
> 
> When will the new repo work ? Keep it up :)

I appreciate your patience and I want to provide you with an update on the repository and the next steps.

Although i there are some minor improvements I would like to make to the architecture, the current version is already kind of functional and can be used for further development. 

Moving forward, the next step is to complete the implementation of the downloading and merging of episodes. However, there is a roadblock due to the yt-dlp dependency not working correctly. You can get more information on the issue here:
https://github.com/yt-dlp/yt-dlp/issues/7037

Rest assured, once the yt-dlp issue is resolved, I will be able to proceed with the implementation of the mentioned functionality. As soon as it is ready, I will provide an in-development preview to try out.
