### ISSUE TITLE
program just crashes

### ISSUE THREAD

**Issue by Vogeluff** [bumbummen99/southparkdownloader#3]
hi there,
so i tried both the gui version and the normal one. both just crash for me. they both create 3 folders and download the youtube-dl.exe into the "dep" one but nothing else happens. no gui opens with the gui version, only a logo that goes away after a while. tried running as admin and running normally. is there an additional manual setup i have to do?

**Comment by bumbummen99** [comment]
No this is a bug. I have not used the tool in a while but there are a multitude of issues:
- [x] The ffmpeg download URL is invalid, this has to be updated with a new one
- [x] SouthPark.de URL format has changed, all episode URLs have to be updated in the episodes.db
- [ ] YoutubeDL is currently *incompatible* to southpark.de since the URL format change. A fix has already been proposed but has to be merged and then released (https://github.com/ytdl-org/youtube-dl/issues/26763). You could for the moment build youtube-dl yourself with the fix applied and then drag it into the deps folder of this tool and it will use it.

**Comment by Vogeluff** [comment]
thanks for the fast reply. are u planning on updating the tool? if so id
rather wait for u to do so than manually do stuff im not too familiar with

Patrick <notifications@github.com> schrieb am Mo., 12. Okt. 2020, 18:03:

**Comment by okh-mzny** [comment]
The outdated URL structure of the downloader will be incompatible with the youtube-dl fix. 
I tried it myself, some URLs that the downloader generates redirect just fine:
`(https://www.southpark.de/alle-episoden/s14e03-thc-versus-kfc -> https://www.southpark.de/folgen/x5mqiz/south-park-thc-versus-kfc-staffel-14-ep-3)`
while others either return the wrong episode 
`(https://www.southpark.de/alle-episoden/s01e08-mr-hankey-der-weihnachtskot -> https://www.southpark.de/folgen/mfcnvu/south-park-damien-staffel-1-ep-10) `
or fail completely. 
This is entirely on the Southpark backend structure, which is apparently prone to failure (I have organzied my South Park downloads with regex, but ran into all kinds of annoyances like mixed and matched regular hyphens and some unicode crap).

**Comment by okh-mzny** [comment]
>You could for the moment build youtube-dl yourself with the fix applied

You couldn't really, the fix in https://github.com/ytdl-org/youtube-dl/issues/26763#issuecomment-705696992 is simply hardcoding an episode ID into the extractor, causing it to always download the same episode (in this case the Pandemic Special)
The actual fix is being developed here: https://github.com/blackjack4494/youtube-dlc/issues/187

**Comment by bumbummen99** [comment]
> 
> 
> The outdated URL structure of the downloader will be incompatible with the youtube-dl fix.
> I tried it myself, some URLs that the downloader generates redirect just fine:
> `(https://www.southpark.de/alle-episoden/s14e03-thc-versus-kfc -> https://www.southpark.de/folgen/x5mqiz/south-park-thc-versus-kfc-staffel-14-ep-3)`
> while others either return the wrong episode
> `(https://www.southpark.de/alle-episoden/s01e08-mr-hankey-der-weihnachtskot -> https://www.southpark.de/folgen/mfcnvu/south-park-damien-staffel-1-ep-10) `
> or fail completely.
> This is entirely on the Southpark backend structure, which is apparently prone to failure (I have organzied my South Park downloads with regex, but ran into all kinds of annoyances like mixed and matched regular hyphens and some unicode crap).
  
@okh-mzny 
Check again :) But make sure to update the episode index first tought it will still fail.

@Vogeluff It also seems like something is wrong with the Installer build. I currently have no time to fix that but you can simply extract the Frontend build from the releases.

**Comment by okh-mzny** [comment]
Yep. Release 1.5.1 got the URLs right. 
Now the only thing that remains is getting youtube-dl to work (you _might_ have to implement youtube-dlc if youtube-dl is too slow to get updated) and we should be good to go.

**Comment by Vogeluff** [comment]
1.5.1 installs fine now. even though i thought it crashed because the logo that starts up just sat there but after a minute or so the program itself opened and as far as i can tell the program itself runs as it should, even though every video gives me "youtubeDL failed." as far as i understand that is a problem with youtube dl and we just have to wait?

a question i have, now that i got the program running for the first time is, how can i select which episodes the program downloads and which languages. i'd love to get german and english, if possible already in 1 file but i assume they are completly different videos on the southpark websites so i'll have to merge them by hand but thats fine.

if i press "download" it seems to try and download EVERYTHING. i assume if i already had episodes in the folder it would skip those? can i select only specific seasons or episodes somehow?

thanks for the super fast replies and fixes so far! really happy :)!

**Comment by okh-mzny** [comment]
youtube-dlc now supports downloading south park episodes from the new site structure:
https://github.com/blackjack4494/youtube-dlc/pull/188
To quickly get the downloader working I suggest using that instead of youtube-dl for now or starting now.

**Comment by bumbummen99** [comment]
I have added an option to use YouTube-DLC instead of the offical version. In order to do so just append the `ytdlc` argument to your startup of SouthParkDL

**Comment by Vogeluff** [comment]
EDIT: I figured it out haha, sorry to bother you. If anyone else struggles with this: just download the youtube-dlc.exe and put it in the "dep" folder where the youtube-dl.exe and others are. then delete the youtube-dl.exe and rename the youtube-dlc.exe to youtube-dl.exe. the program then just uses that. awesome!

> I have added an option to use YouTube-DLC instead of the offical version. In order to do so just append the `ytdlc` argument to your startup of SouthParkDL

awesome! but could you elaborate on how to do that please? i know how to start and type in a command line terminal but i don't know what appent the ytdlc argument means.. i tried just typing that into the command line but that just errors. 

if you find the time a simple explaination on how to use youtube dlc would be great!

**Comment by bumbummen99** [comment]
> EDIT: I figured it out haha, sorry to bother you. If anyone else struggles with this: just download the youtube-dlc.exe and put it in the "dep" folder where the youtube-dl.exe and others are. then delete the youtube-dl.exe and rename the youtube-dlc.exe to youtube-dl.exe. the program then just uses that. awesome!

That will also work tought you can also start it with the `ytdlc` argument and it will do that automatically. To do so, just open a CMD inside the directory where SouthParkDL is extracted to and run `./SouthParkDL.exe ytdlc` or create an link to the file and add the argument after the path 👍

**Comment by Vogeluff** [comment]
> > EDIT: I figured it out haha, sorry to bother you. If anyone else struggles with this: just download the youtube-dlc.exe and put it in the "dep" folder where the youtube-dl.exe and others are. then delete the youtube-dl.exe and rename the youtube-dlc.exe to youtube-dl.exe. the program then just uses that. awesome!
> 
> That will also work tought you can also start it with the `ytdlc` argument and it will do that automatically. To do so, just open a CMD inside the directory where SouthParkDL is extracted to and run `./SouthParkDL.exe ytdlc` or create an link to the file and add the argument after the path 👍

Awesome! I tried that using a shortcut but i must've messed it up. whatever. now we have 3 working ways :D

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
