### ISSUE TITLE
[Suggestion] Configurable Episode naming scheme

### ISSUE THREAD

**Issue by okh-mzny** [bumbummen99/southparkdownloader#6]
Hello!

I find the naming scheme of the downloader a bit dry for my taste. 
I've wrote some regex for personal use to convert the Youtube-dl output filenames (with metadata like release date) into a beautified format. You can see it below:

![image](https://user-images.githubusercontent.com/60819623/95782712-9eb00a00-0cd0-11eb-9796-56018c69d719.png)

Now, as every South Park episode got re-released in HD, I'd like to restock my private stash a bit, but after discovering this downloader I feel too lazy to dig up all of my old download and combining scripts again :')

Now my suggestion is giving the postprocessor the option to set your own formatted naming scheme (say %t for Title or %d for release date, %s for season and %e for episode number)

This would be cool! 

Cheers

**Comment by bumbummen99** [comment]
It seems like something went wrong, the parts should get merged by ffmpeg and be saved as `Season/Episode name` in a single file with the name as a proper media tag.

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
