### ISSUE TITLE
Youtube-dl failed and ffmpeg cannot be downloaded

### ISSUE THREAD

**Issue by marvelino1** [bumbummen99/southparkdownloader#7]
Hey,

I get the following error message within the setup process:

_"Could not download ffmpeg, please contact the developer and/or make sure that the hardcoded uri is still valid. Error: The remote server returned an error: (404) Not Found."_

When I am trying to start the download I get the following error messages:

_"[S1E3] YoutubeDL failed.
[S1E3] No video files to merge!"_

It would be nice if you could fix those issues. Thank you in advance!

**Comment by bumbummen99** [comment]
The old FFMPEG build hoster has gone offline. Refactored to use latest builds provided by gyan.dev.

Additionally there is currenlty an issue with YouTubeDL, it is simply not compatible to SouthPark.de right now, we have to wait for the fix to be merged or use YoutubeDLCommunity instead.

#3
https://github.com/ytdl-org/youtube-dl/issues/26763
