### ISSUE TITLE
When using youtube-dlc the files will not be merged, neither automatically nor when trying to force it with command

### ISSUE THREAD

**Issue by Vogeluff** [bumbummen99/southparkdownloader#8]
Yeah, I just downloaded all the episodes with the help of using youtube-dlc (Thanks so much for implementing that!!) but when it came to processing I always got error messages. When I just out of interested tried pressing download again it started downloading everything again, so I assume that it's not recognizing the name scheme of the files or something, maybe due to youtube-dlc being different in that regard?

Episode 1 for example has it's files named like this (All of the files and episodes are named like this, don't know how that may differ from using youtube-dl since that's not working for me at all: 

South Park _ Cartman Gets An Anal Probe _ E 0101 _ HDSS0101X deu _ Version - 634267 _ Comedy Central S1-f46ac634-1f72-4b9d-a38a-4c0c900f8a3e

If anyone has ideas I'd be very thankful! Of course, manually merging the parts is an O P T I O N, but the benefit of this tool would mostly be saving time, so for me that would defeat the point.

PS: I tried using both the GUI and the command program. No differences there...

**Comment by bumbummen99** [comment]
I think the sorting is currently broken, if i recall that correctly they once were named like 'Act 1', 'Act 2' and so on. I'll have to look into how the parts are named and rewrite the sorting logic for the new file names. Also it should not redownload the parts but try to merge them instead, i'll have to sort that out aswell :smile:

**Comment by Vogeluff** [comment]
awesome! it seems like they just changed the wording. its now S1, S2 and so on. seems to be in correct order for the episodes i "tested"

**Comment by bumbummen99** [comment]
I just tried to debug it but it does seem that dl/dlc is now incompatible to southpark.de again :/

```
PS F:\Workspace\Repos\SouthParkDLCommandLine\bin\Debug\netcoreapp3.1\dep> ./youtube-dl.exe https://www.southpark.de/folgen/940f8z/south-park-cartman-und-die-analsonde-staffel-1-ep-1
[generic] south-park-cartman-und-die-analsonde-staffel-1-ep-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] south-park-cartman-und-die-analsonde-staffel-1-ep-1: Downloading webpage
[generic] south-park-cartman-und-die-analsonde-staffel-1-ep-1: Extracting information
```

**Comment by Vogeluff** [comment]
I just tried downloading again (keep in mind i use youtube dlc) and it works for me. the merging doesn't, that's the problem. i don't see how that would be connected to youtube dl/dlc compatability besides the naming scheme being updated though..

**Comment by bumbummen99** [comment]
> 
> 
> I just tried downloading again (keep in mind i use youtube dlc) and it works for me. the merging doesn't, that's the problem. i don't see how that would be connected to youtube dl/dlc compatability besides the naming scheme being updated though..

That's strange, just out of interest did you update the dependencies / ytdl when downloading again? it might be that the current version broke something again but i am not 100% sure. If you can, can you check what is the output of `youtube-dl.exe --version`?

**Comment by Vogeluff** [comment]
i didn't update the dependencies since i first had it working. version of my youtube-dlc.exe is "2020.11.11-3" according to powershell :D i can send you the file if that could help

**Comment by Vivida1** [comment]
Also getting
```
[S1E2] Starting download 2 Wie werde ich zum Kampfkoloss?
[S1E4] Starting download 4 Ein Heim für Tiertunten
[S1E3] Starting download 3 Knall endlich den Hasen ab!
[S1E1] Starting download 1 Cartman und die Analsonde
[S1E2] Finished download
Processing episode error: Input string was not in a correct format.
``` 

Seems to be a trivial fix since youtube-dlc outputs the files now as
```
'South Park _ Cartman Gets An Anal Probe _ E 0101 _ HDSS0101X deu _ Version - 634267 _ Comedy Central S1-f46ac634-1f72-4b9d-a38a-4c0c900f8a3e.mp4'
'South Park _ Cartman Gets An Anal Probe _ E 0101 _ HDSS0101X deu _ Version - 634267 _ Comedy Central S2-33ffda31-83e5-4a4c-b7e6-f982c8e57748.mp4'
'South Park _ Cartman Gets An Anal Probe _ E 0101 _ HDSS0101X deu _ Version - 634267 _ Comedy Central S3-da0ec5d8-05ea-45fa-aa88-387b670658f7.mp4'
'South Park _ Cartman Gets An Anal Probe _ E 0101 _ HDSS0101X deu _ Version - 634267 _ Comedy Central S4-22a23f94-dc55-4d76-a3fe-eda2df17b8a7.mp4'
```

**Comment by Vogeluff** [comment]
awesome! looking forward to it. manually merged the firsted episode using
mkvgui and besides the naming everything else seems ro be fine with the
files :)

Vivida ***@***.***> schrieb am Di., 9. März 2021, 21:31:

**Comment by bumbummen99** [comment]
So i think i fixed it with 1.7.1, so it should now work again 👍 Please keep in mind that the releases are now built and published automatically so i am not 100% sure if they work or are packaged corrctly.

**Comment by Vogeluff** [comment]
awesome that you keep up the good work :) just downloaded the newest version (use the command line for now since i dont know what the DLUI is and it doesnt seem to do anything when i click the exe haha).

i couldnt just process my already downloaded files but i just started to download them fresh hope this time it will work.

any progress on maybe implementing english support? if you tell me how i would really love to maybe create the english index. just give me (or direct me to where i can find it myself) a file with the german links and i will one by one exchange them for the english ones. then, it wouldnt even need implementation. it could just be manually swapped out. but, having the option to choose from both of them in the program would be cool still haha (or even have the ability to merge both audio tracks ton 1 video file.. that would be my holy grail wish for this)

best wishes from germany!

**Comment by Vogeluff** [comment]
soooo.... i just tested around editing the data.db with "DB Browser for SQLite", changing the episode names and url to english. the downloader will recognize the new name but it will fail to download claiming "YoutubeDL failed." and "No video files to merge!"

is it more difficult than that? i assumed it would just go to the urls in that table, download the files and name them accordingly to the name that is in the table :/ really want this to work haha, i will do as much as i can, maybe you have an easy idea

**Comment by bumbummen99** [comment]
So it seems that it does work now, but there still is one issue:
Somehow the latest yt-dlc is NOT the latest. When i download the latest release from the youtube-dlc releases it has a different hash than when i download it using this url:
https://github.com/blackjack4494/youtube-dlc/releases/latest/download/youtube-dlc.exe

That is causing the software to download the wrong version of ytdl but i have not time yet to figure it out why. Seems to be an issue with github that would require the software to first fetch the releases and take the latest manually (ouch).

**Comment by bumbummen99** [comment]
> 
> 
> awesome that you keep up the good work :) just downloaded the newest version (use the command line for now since i dont know what the DLUI is and it doesnt seem to do anything when i click the exe haha).
> 
> i couldnt just process my already downloaded files but i just started to download them fresh hope this time it will work.
> 
> any progress on maybe implementing english support? if you tell me how i would really love to maybe create the english index. just give me (or direct me to where i can find it myself) a file with the german links and i will one by one exchange them for the english ones. then, it wouldnt even need implementation. it could just be manually swapped out. but, having the option to choose from both of them in the program would be cool still haha (or even have the ability to merge both audio tracks ton 1 video file.. that would be my holy grail wish for this)
> 
> best wishes from germany!

I have not yet had time to test it but normally it should work by just providing the english url, but keep in mind to use the current YouTubeDL Community fork as the main version right now is still not compatible with southpark.de/.com 👍 

I think the best way to implement it is to add an english url and title to the .db so the software can download and rename them properly.

**Comment by Vogeluff** [comment]
awesome! it already works for the de episodes but the english as i said i can't get to work. i think the tool im using which gives me a table of all the entries, somehow isnt formatting it correct maybe? i will definetly try with the updated ytdlc as you suggested, maybe that will already solve it. thanks for your work!

**Comment by Vogeluff** [comment]
hm so i tried with your linked youtube dlc but no difference. if i edit the data.db with the tool i found and open it later after changes in notepad++ its obviously not really readable BUT i can find the german urls still in there which makes me think the tool im using is not really great at editing this database haha. or is there something like a cache in the program that i have to clean inbetween testing? how did you create the databse, is there an easy way to just do the same or create it somewhere else and send you the finished file?

**Comment by bumbummen99** [comment]
> 
> 
> hm so i tried with your linked youtube dlc but no difference. if i edit the data.db with the tool i found and open it later after changes in notepad++ its obviously not really readable BUT i can find the german urls still in there which makes me think the tool im using is not really great at editing this database haha. or is there something like a cache in the program that i have to clean inbetween testing? how did you create the databse, is there an easy way to just do the same or create it somewhere else and send you the finished file?

What tool are you using to edit the db? It is an SQLiteDB so i would suggest using an SQL editor/viewer :D I can only recommend DBEaver and Navicat Lite on Windows for that purpose 👍 At best the .db would contain booth the german and english URLs

**Comment by Vogeluff** [comment]
"DB Browser for SQLite" is what i used. will check out dbeaver. thanks!

**Comment by Vogeluff** [comment]
sooooo... turns out if i add a german episode to the db (added the new impfspecial 24x2) to the databse that works. so its not how i edit it, something with the english files is different :/ i tried both the english episodes hosted on southpark.de and the ones on southparkstudios.com

shame. thought maybe i could help with that. maybe its just a youtube dlc problem that its not compatible with those episodes for whatever reason? i mean, the program gives me that "YoutubeDL failed." error. it also gives me that for some specific german episodes btw (2x1 and 2x6). maybe it could be some problem in the naming on the website? maybe they made some faults for those episodes AND the english ones are just different.. thats my analysis so far hahaha

**Comment by bumbummen99** [comment]
You could try to just run `youtube-dlc.exe URLToVideo` to see if it is working at all, that way you would get more verbose output. But please keep in mind #11 . Right now you will have to go to https://github.com/blackjack4494/youtube-dlc/releases and download the latest release manually

**Comment by Vogeluff** [comment]
i dont really know how to just run that. im at my limits here it wise haha

Patrick ***@***.***> schrieb am Sa., 17. Apr. 2021, 19:40:

**Comment by bumbummen99** [comment]
It seems that it is right now not compatible with the southpark.de/en URL scheme:
```
PS H:\SouthParkDL\dep> .\youtube-dlc.exe https://www.southpark.de/en/episodes/940f8z/south-park-cartman-gets-an-anal-probe-season-1-ep-1
[generic] south-park-cartman-gets-an-anal-probe-season-1-ep-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] south-park-cartman-gets-an-anal-probe-season-1-ep-1: Downloading webpage
[generic] south-park-cartman-gets-an-anal-probe-season-1-ep-1: Extracting information
ERROR: Unsupported URL: https://www.southpark.de/en/episodes/940f8z/south-park-cartman-gets-an-anal-probe-season-1-ep-1
PS H:\SouthParkDL\dep> .\youtube-dlc.exe https://www.southpark.de/folgen/940f8z/south-park-cartman-und-die-analsonde-staffel-1-ep-1
[southpark.de] south-park-cartman-und-die-analsonde-staffel-1-ep-1: Downloading webpage
...
```

Maybe it is possible by directly using [southpark.cc.com](https://southpark.cc.com) but that will redirect german users directly to southpark.de. To do that i guess a VPN would be required

**Comment by Vogeluff** [comment]
i already tried cc.com with vpn active (also canadas site lol) but it didnt
work either :/

Patrick ***@***.***> schrieb am Sa., 17. Apr. 2021, 19:56:

**Comment by Vogeluff** [comment]
sooo i downloaded all the episodes now (including the newest 24x2) and even when running it multiple times or using a fresh install some specific episodes get different kinds of errors. hope i dont get on your nerves, just thought it might be helpful info for you once you find time to maybe work on it if you'd like. [HERE IS A SCREENSHOT OF THE ERRORMESSAGES](https://i.postimg.cc/nhZ3MZV0/2021-04-18-15-59-50-D-In-Bearbeitung-Serien-South-Park-1996-South-Park-DLCommand-Line-1-7-1-win-x64.png)

kind regards

**Comment by DrHardReset** [comment]
How did you fix your yesterdays problem? I get the same error while using the latest version from https://github.com/blackjack4494/youtube-dlc/releases.

```youtube-dlc.exe https://www.southpark.de/en/episodes/940f8z/south-park-cartman-gets-an-anal-probe-season-1-ep-1
[generic] south-park-cartman-gets-an-anal-probe-season-1-ep-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] south-park-cartman-gets-an-anal-probe-season-1-ep-1: Downloading webpage
[generic] south-park-cartman-gets-an-anal-probe-season-1-ep-1: Extracting information
ERROR: Unsupported URL: https://www.southpark.de/en/episodes/940f8z/south-park-cartman-gets-an-anal-probe-season-1-ep-1```

**Comment by Vogeluff** [comment]
if you mean me i didnt fix the englisv url problem. i assume gor now they just aren't supported sadly

**Comment by DrHardReset** [comment]
I get the same errors for the german urls.

**Comment by Vogeluff** [comment]
are you using ytdlc? other than that i just use the program as is with the latest update. what location are you in? if not germany you may need a vpn i dont know.

**Comment by DrHardReset** [comment]
I don't understand why , but when I clone the https://github.com/blackjack4494/youtube-dlc repo and build it myself, the program works for me with german urls. I would have expected the url changes of southpark.de to be included in the latest release of youtube-dlc, but this seems not to be the case.

**Comment by Vogeluff** [comment]
i downloaded the newest version and for me it works.

DrHardReset ***@***.***> schrieb am So., 25. Apr. 2021, 18:38:

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
