### ISSUE TITLE
[Suggestion] Giving the option for ENG and GER versions, maybe even merging them automatically with ffmpeg

### ISSUE THREAD

**Issue by Vogeluff** [bumbummen99/southparkdownloader#9]
southpark.de both hosts englisch and german versions of the episodes. the only difference from the URL and watching the first episode seems to be the language, the video files SEEM to be the same. maybe specific episodes have changes though, I don't know.

from the url, the only difference is that the german episodes are like this: "southpark.de/folgen/940f8z/south-park-cartman-und-die-analsonde-staffel-1-ep-1" and the english ones have "/en" added and "folgen" and the episodes title translated, see here: "https://www.southpark.de/en/episodes/940f8z/south-park-cartman-gets-an-anal-probe-season-1-ep-1" the random code is the same (in this case "940f8z"). 

I assume that could be implemented the same way the german episodes are right now and maybe you could choose what languages you want and if you want seperate files or merged ones (merged meaning 1 video file with 2 selectable audio tracks). as far as i understand ffmpeg (i use mkvtoolnixgui quite often and think they are similar) that is easily doable for a single episode. 

I don't claim to know if programming it to do it for all episodes is as simple or if that's lots of work but it would be a suuuuper awesome feature in my opinion, especially with comedies having the option of the original language is great! I also just noticed that both the english and german versions BOTH have the english subtitles included, no german ones at all on the side. if they are a common format, maybe those could also be a downloadable toggle to be included in the final file? would help some people who are not that good at english but wanna try it maybe.

I really, really, really hope this doesn't come off as demanding, I'd be happy to help out if for example you would explain to me in what format to write the database with the english URLs. as long as it's just copying URLs and formatting correctly I would be good haha, just don't know programming at all. really like the program!

**Comment by TH42** [comment]
deutsch.db: corrections and addition (S24E02) for data.db
english.db: episodes in english (alternative data.db)
[spdata.zip](https://github.com/bumbummen99/southparkdownloader/files/6417533/spdata.zip)

**Comment by Vogeluff** [comment]
> deutsch.db: corrections and addition (S24E02) for data.db
> english.db: episodes in english (alternative data.db)
> [spdata.zip](https://github.com/bumbummen99/southparkdownloader/files/6417533/spdata.zip)

thanks for the effort but the english files just fail to download? and the german one, besided the addition of 24e2, seems to be the same? the exact same handful episodes that fail in the regular german data.db file fail with yours.

i tried both youtube dlc and youtube dl. any idea what i could do different? is it working for you?

**Comment by bumbummen99** [comment]
> deutsch.db: corrections and addition (S24E02) for data.db
> english.db: episodes in english (alternative data.db)
> [spdata.zip](https://github.com/bumbummen99/southparkdownloader/files/6417533/spdata.zip)

Awesome work! Would you mind creating an PR adding those files to the /docs folder of the repository? You can do that using the GitHub web interface by clicking create file, it will then automatically fork the repository for you and also show a button to create an PR :+1:

**Comment by TH42** [comment]
> thanks for the effort but the english files just fail to download? and the german one, besided the addition of 24e2, seems to be the same? the exact same handful episodes that fail in the regular german data.db file fail with yours.
> 
> i tried both youtube dlc and youtube dl. any idea what i could do different? is it working for you?

Alas it's not. I made the english db in preparation to download the english language tracks, but didn't test the download before commenting. The links are correct, though, it's just an issue with ytdlc being unable to process them.
The german db in the repo has quite a few hickups. The downloaded episodes are not always what they claim to be. Check "Scott Tenorman" for example: it downloads as episode 1 of season 5, when in fact it's episode 4, which is labeled "Die Liga der Super Besten Freunde". I fixed these hickups and added episode 2 of season 24. S5E3 "Super Best Friends", S10E3+4 "Cartoon Wars", and S14E3+4 are marked as "Currently unavailable". If you follow the link you will find that there's no video, just a message. They will keep failing until an actual video is supplied by the site.

**Comment by TH42** [comment]
> Would you mind creating an PR adding those files to the /docs folder of the repository? You can do that using the GitHub web interface by clicking create file, it will then automatically fork the repository for you and also show a button to create an PR 👍

I'll give it a try. Quite some time since I last used git.

Edit: Done ... I hope.

**Comment by Vogeluff** [comment]
ahhhh thanks for the answear and effort! i never noticed the wrong episodes haha but yeah i know about the missing episodes that there are, but there are actually a couple more episodes that fail to download completly every time i try it even tjough they sre up on the side. its only 3 or so, have to check. not on my pc right now

**Comment by TH42** [comment]
Regarding subtitles: These can be downloaded too, but ...
I did that on the 2 episodes of season 24 which works just fine, because these episodes download as 1 video file each - no stitching necessary.
I then tried the same for S1E1. This one - and I think the same is true for all other episodes throughout the seasons except 24 - downloads in parts. That goes for the subtitles as well. Of course you can stitch these too, but you have to fake a subtitle entry in every part but the last that aligns with the runtime of the corresponding video part. Otherwise the subtitles will be out of sync beginning with the 2nd part.

**Comment by Vogeluff** [comment]
weeeird but interesting! if i stitched my 2 part lord of the rings
blurayrip it also stitched the subtitles without it gettinc out of sync 🤔

TH42 ***@***.***> schrieb am Di., 4. Mai 2021, 22:48:

**Comment by TH42** [comment]
I made a PR for yt-dlc to support the english episodes.
`https://github.com/blackjack4494/youtube-dlc/pull/225/files`

**Comment by bumbummen99** [comment]
> I made a PR for yt-dlc to support the english episodes.
> `https://github.com/blackjack4494/youtube-dlc/pull/225/files`

Yesterday your GIT skills were rusty and today you contribute to YTDL :) You are fire buddy, keep it up 🔥 🚀 <3

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
